extensions:
  basicauth:
    htpasswd:
      inline: |
        ${env:OTEL_BASIC_AUTH_HTPASSWD}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth

processors:
  batch:
    timeout: 1m
    send_batch_size: 8192
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

exporters:
  clickzetta:
    service: ${env:CLICKZETTA_SERVICE}
    username: ${env:CLICKZETTA_USERNAME}
    password: ${env:CLICKZETTA_PASSWORD}
    workspace: ${env:CLICKZETTA_WORKSPACE}
    virtual_cluster: ${env:CLICKZETTA_VC}
    instance: ${env:CLICKZETTA_INSTANCE}
    schema: public
    create_schema: true
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickzetta]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickzetta]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickzetta]
