// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/apikeyrouting component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("apikeyrouting")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/connector/apikeyroutingconnector"
)

const (
	TracesToTracesStability   = component.StabilityLevelAlpha
	MetricsToMetricsStability = component.StabilityLevelAlpha
	LogsToLogsStability       = component.StabilityLevelAlpha
)
